'use client';

import { useEffect, useState } from 'react';
import { User, Building } from 'lucide-react';

const testimonials = [
  {
    text: "LegalDraw AI has revolutionized how we handle document generation. What used to take hours now takes minutes.",
    author: "Sarah Chen",
    role: "Senior Partner",
    company: "Chen & Associates"
  },
  {
    text: "The accuracy and consistency of the documents generated by LegalDraw AI is remarkable. A game-changer for our practice.",
    author: "Michael Rodriguez",
    role: "Legal Director",
    company: "Global Legal Solutions"
  },
  {
    text: "We've seen a 70% reduction in document preparation time since implementing LegalDraw AI. The ROI is undeniable.",
    author: "Emma Thompson",
    role: "Managing Partner",
    company: "Thompson Legal"
  }
];

export function Testimonials() {
  const [current, setCurrent] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrent((prev) => (prev + 1) % testimonials.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="space-y-6">
      <p className="text-xl font-medium">"{testimonials[current].text}"</p>
      
      <div className="flex items-center gap-4">
        <div className="w-10 h-10 rounded-full bg-zinc-800 flex items-center justify-center">
          <User className="w-5 h-5" />
        </div>
        <div>
          <div className="font-medium">{testimonials[current].author}</div>
          <div className="text-sm text-zinc-400 flex items-center gap-2">
            {testimonials[current].role} · {testimonials[current].company}
          </div>
        </div>
      </div>
    </div>
  );
}